services:
  - type: web
    name: gemini-api-tester-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 